SUPABASE_URL = "https://jnvknirvyqgngzernqdp.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpudmtuaXJ2eXFnbmd6ZXJucWRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQyNTgxMTQsImV4cCI6MjA4OTgzNDExNH0.7n51U5Vsr9S-LHrJWQkarPxGF6TmaFtNmigwKpjYVfQyour-super-long-anon-key-goes-here"
